### ISSUE TITLE
Ocultar funcionalidades

### ISSUE THREAD

**Issue by jmg0137** [jmg0137/3D-Viewer-v2.0#12]
Ocultar al usuario que no sea el administrador ciertas funcionalidades

**Comment by jmg0137** [comment]
En cuanto a la manera de ocultar los botones correspondientes, para poder dar la funcionalidad que quiero lo mejor sería usar el Flask Login, lo que pasa es que no se crear una clase User (UserMixing) en la que meter mis propios métodos para hacer las comprobaciones correspondientes (Utilizando las plantillas de Django para las posteriores comprobaciones).

Con JQuery se puede ocultar, pero no se como ocultar en función de cierto parámetro, que en este caso hay que obtenerlo de la base de datos, o de alguna variable, la cual no se donde almacenar para obtener después

Gracias.

**Comment by joseFranciscoDiez** [comment]
Podrías hacer una prueba de concepto (un proyecto mínimo que solo tenga login y dos roles), basándote en lo que se propone en este hilo de stackoverflow https://stackoverflow.com/questions/15871391/implementing-flask-login-with-multiple-user-classes

Una solución consiste en crear una Clase User que tiene un atributo urole, después como flask-login no tiene soporte de roles, implementa su propia versión de login_required y puede denegar el acceso a una vista no solo si el usuario no está autenticado, como si el usuario lo está pero no es del rol que usa la vista.

Después habría que tener una vista para cada rol. Y para no tener código duplicado todas las cosas comunes estarían en la plantilla padre y con herencia de plantillas en las hijas se añaden los botones o partes específicas de cada rol.

https://docs.djangoproject.com/en/1.7/topics/templates/#custom-libraries-and-template-inheritance

**Comment by jmg0137** [comment]
Vale si, el tema de la plantilla me parece lo mejor, y redirigir a la plantilla correspondiente, pero el visor en sí, también extiende de la plantilla padre (la que ve el administrador) y en el caso de que sea usuario, habría que cambiar en todas las plantillas a la que quieres redirigir., es decir, en lugar desde el login ir a 'modelos', tendré que mandarlos a 'modelos_usuario', lo que conllevaría a tener que cambiar los todos las redirecciones.

No veo que haya problema en hacerlo ya que solo es crear cada una de las plantillas para los usuarios y cambiar el bloque correspondiente y no habría duplicación de código, pero quiero saber si queréis hacerlo así.

**Comment by jmg0137** [comment]
Lo he resuelto creando una plantilla que hereda de otra, y he añadido el campo rol al usuario (UserMixin) con lo que puedo comprobar si es administrador o usuario y así poder elegir que plantilla elijo (Administrador o Usuario)
