### ISSUE TITLE
Generar documentación Servidor

### ISSUE THREAD

**Issue by jmg0137** [jmg0137/3D-Viewer-v2.0#139]

**Comment by jmg0137** [comment]
No consigo generar la documentación del servidor con el comando "npm run pydoc-http" ni "npm run pydoc-style". Me genera este error desde Linux (ya que desde Windows me dice que no tiene instalado 'make'):

jose@jose:~/Escritorio/3D-Viewer-v2.0$ npm run pydoc-http

> 3d-viewer-v2@0.9.0 pydoc-http /home/jose/Escritorio/3D-Viewer-v2.0
> make --directory ./Documentación/python -f Makefile html

make: se entra en el directorio '/home/jose/Escritorio/3D-Viewer-v2.0/Documentación/python'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/__main__.py", line 14, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/sphinx/__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "/usr/lib/python3/dist-packages/sphinx/__init__.py", line 61, in build_main
    from sphinx import cmdline
  File "/usr/lib/python3/dist-packages/sphinx/cmdline.py", line 14, in <module>
    import optparse
  File "/usr/lib/python3.5/optparse.py", line 421, in <module>
    _builtin_cvt = { "int" : (_parse_int, _("integer")),
  File "/usr/lib/python3.5/gettext.py", line 529, in gettext
    return dgettext(_current_domain, message)
  File "/usr/lib/python3.5/gettext.py", line 493, in dgettext
    codeset=_localecodesets.get(domain))
  File "/usr/lib/python3.5/gettext.py", line 428, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/usr/lib/python3.5/gettext.py", line 385, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib/python3.5/gettext.py", line 114, in _expand_lang
    loc = locale.normalize(loc)
AttributeError: module 'locale' has no attribute 'normalize'
Makefile:20: fallo en las instrucciones para el objetivo 'html'
make: *** [html] Error 1
make: se sale del directorio '/home/jose/Escritorio/3D-Viewer-v2.0/Documentación/python'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! 3d-viewer-v2@0.9.0 pydoc-http: `make --directory ./Documentación/python -f Makefile html`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the 3d-viewer-v2@0.9.0 pydoc-http script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jose/.npm/_logs/2018-01-24T18_48_39_497Z-debug.log

**Comment by alvarag** [comment]
¿Has buscado en internet por qué puede ser el fallo?
¿Has revisado el log que te dice? 

```
2018-01-24T18_48_39_497Z-debug.log
```

**Comment by jmg0137** [comment]
He buscado pero tampoco es que halla un error exacto, simplemente que falla en el script correspondiente, ya que cada persona genera los scripts que quiere y con el nombre que quiere, por lo que se me está haciendo difícil encontrarlo.

El log tampoco es que sirva de mucha ayuda:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/local/bin/npm', 'run', 'pydoc-http' ]
2 info using npm@5.6.0
3 info using node@v7.10.1
4 verbose run-script [ 'prepydoc-http', 'pydoc-http', 'postpydoc-http' ]
5 info lifecycle 3d-viewer-v2@0.9.0~prepydoc-http: 3d-viewer-v2@0.9.0
6 info lifecycle 3d-viewer-v2@0.9.0~pydoc-http: 3d-viewer-v2@0.9.0
7 verbose lifecycle 3d-viewer-v2@0.9.0~pydoc-http: unsafe-perm in lifecycle true
8 verbose lifecycle 3d-viewer-v2@0.9.0~pydoc-http: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jose/Escritorio/3D-Viewer-v2.0/node_modules/.bin:/home/jose/bin:/home/jose/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle 3d-viewer-v2@0.9.0~pydoc-http: CWD: /home/jose/Escritorio/3D-Viewer-v2.0
10 silly lifecycle 3d-viewer-v2@0.9.0~pydoc-http: Args: [ '-c',
10 silly lifecycle   'make --directory ./Documentación/python -f Makefile html' ]
11 silly lifecycle 3d-viewer-v2@0.9.0~pydoc-http: Returned: code: 2  signal: null
12 info lifecycle 3d-viewer-v2@0.9.0~pydoc-http: Failed to exec pydoc-http script
13 verbose stack Error: 3d-viewer-v2@0.9.0 pydoc-http: `make --directory ./Documentación/python -f Makefile html`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:194:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid 3d-viewer-v2@0.9.0
15 verbose cwd /home/jose/Escritorio/3D-Viewer-v2.0
16 verbose Linux 4.13.0-26-generic
17 verbose argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "pydoc-http"
18 verbose node v7.10.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error 3d-viewer-v2@0.9.0 pydoc-http: `make --directory ./Documentación/python -f Makefile html`
22 error Exit status 2
23 error Failed at the 3d-viewer-v2@0.9.0 pydoc-http script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

He mirado el Makefile pero tampoco hay nada que pueda estar fallando, aunque igual hay algo que aún se me escapa.

**Comment by alvarag** [comment]
Supongo que será un tema de versiones, no pierdas mucho más el tiempo y podría generarse desde mi equipo.

Por cierto @joseFranciscoDiez  y @jmg0137, como mañana está cerrado el edificio, ¿cuando hacemos la reunión semanal? ¿misma hora el martes?

**Comment by joseFranciscoDiez** [comment]
Por mi ningún problema con el martes.

**Comment by alvarag** [comment]
Pues el martes a la misma hora. En realidad mañana siguen abiertas las salas de estudio y nosotros pidiendo autorización podemos pasar, pero creo que es mejor posponerlo un día.
Jose, ¿se sabe algo del operador?
