### ISSUE TITLE
Integración del proyecto en un servidor público

### ISSUE THREAD

**Issue by jmg0137** [jmg0137/3D-Viewer-v2.0#14]

**Comment by jmg0137** [comment]
Sigo teniendo el problema que os comenté y no consigo avanzar

**Comment by joseFranciscoDiez** [comment]
Me han respondido del servicio de informática que en una semana aproximadamente podremos contar con una máquina con python3, pip3 y git.

Así que esta tarea puede quedar de momento aplazada hasta ver si el servidor que nos ponen en la ubu cumple nuestras espectativas.

**Comment by alvarag** [comment]
¡¡Muy buenas noticias!! Mantennos informados Jose.

**Comment by jmg0137** [comment]
Creo que puedo tener la estructura correcta para poder ejecutar la aplicación en Heroku, pero voy a esperar a ver si el servidor de la ubu nos vale. (La ayuda a sido proporcionada por Jazriel (Javier Martínez Riveras))
