### ISSUE TITLE
Documentar plan de proyecto

### ISSUE THREAD

**Issue by jmg0137** [jmg0137/3D-Viewer-v2.0#147]

**Comment by alvarag** [comment]
Revisa la documentación, la versión de los tex que está subida me da fallo al compilar. Supongo que no será la última versión de la documentación.

**Comment by jmg0137** [comment]
Ya está subida la versión que compila

**Comment by alvarag** [comment]
Pero no la de anexos, ¿no?

Adjunto comentarios en memoria

[memoriaC.pdf](https://github.com/jmg0137/3D-Viewer-v2.0/files/1653042/memoriaC.pdf)

**Comment by jmg0137** [comment]
En principio lo que yo tengo está actualizado y si que compila y se visualiza. ¿En que apartado en concreto te falla?
