### ISSUE TITLE
Correcciones documentación

### ISSUE THREAD

**Issue by alvarag** [jmg0137/3D-Viewer-v2.0#158]
Me está dando errores al intentar compilar la memoria, si utilizas "_" en la bibliografía, debes escaparlo con ```\_``` como en mod_wsgi de la Wiki.

También tienes un par de warnings:

- Warning--to sort, need author or key in json:jsnomate
- Warning--empty publisher in apirestbook

Creo que te faltan archivos por subir de los anexos (diagramas de casos de uso) y no puedo compilar.

[memoriaC.pdf](https://github.com/jmg0137/3D-Viewer-v2.0/files/1674446/memoriaC.pdf)

**Comment by joseFranciscoDiez** [comment]
En anexos, en el apartado de requisitos.  Me da problema esta parte, porque el nombre de las imágenes: nivel1 ... es en mayúscula en los ficheros. Puede que este sea un problema solo de usuarios de Linux. Pero la mayoría del tribunal usa Linux.
\imagen{nivel1}{Nivel 1 del diagrama de casos de uso.}{0.9}
\imagen{nivel2}{Nivel 2 del diagrama de casos de uso.}{0.9}
\imagen{nivel3}{Nivel 3 del diagrama de casos de uso.}{0.9}

Se arregla simplemente poniendo Nivel1 etc en mayúsculas
