### ISSUE TITLE
Comentarios menores en memoria y anexos

### ISSUE THREAD

**Issue by alvarag** [jmg0137/3D-Viewer-v2.0#172]
Adjunto versión con correcciones mínimas en la memoria.
[memoriaC.pdf](https://github.com/jmg0137/3D-Viewer-v2.0/files/1710415/memoriaC.pdf)

El *.tex* de anexos no soy capaz de compilarlo: revisa que sea la última versión.

**Comment by jmg0137** [comment]
Para el URL que me pides que ponga con listings, se sale de la página aún más que la imagen. He puesto \basicstyle=\tiny pero aún así se sale. En principio ese es el tamaño más pequeño así que no se si puedo hacerlo más aún
