### ISSUE TITLE
Arreglar tratamiento de decimales para encriptación

### ISSUE THREAD

**Issue by jmg0137** [jmg0137/3D-Viewer-v2.0#50]

**Comment by jmg0137** [comment]
Tengo un problema, y es que tras concatenar la parte entera con la decimal es necesario el paso a float(). pero este cambio solo almacena 15 números incluyendo ambas partes. Con lo cual si nuestra valor es:
-34.81150817871094, nuestro resultado de operación es: -238.811508178711

Se ve que los tres últimos dígitos (094) los redondea, y no se hasta que punto afectará. He encontrado la clase decimal, pero al convertirlo a float tengo el mismo problema

**Comment by alvarag** [comment]
¿Por qué es necesario pasarlo a float? ¿No lo puedes guardar como si fuera texto? Luego ya lo convertirás a float en la decodificación.

**Comment by jmg0137** [comment]
Lo he pensado, pero parece ser que la "librería" encargada de leer el archivo guarda los valores en float para escribirlos. Lo he intentado guardar en string, pero me da error a la hora de escribir el archivo ply

**Comment by alvarag** [comment]
Bueno, no creo que por dos decimales vaya a haber problemas... Habrá que probarlo no obstante.

**Comment by jmg0137** [comment]
![image](https://user-images.githubusercontent.com/32061421/32457146-48b776f0-c328-11e7-9641-97a7f64232b4.png)

Este es el resultado después de la desencriptación. Como pensaba los decimales afectan al resultado.

Otra idea que se me ocurre es cambiar la parte de las caras que se encuentra debajo de la de los vertices, y que es entera, aunque conllevaría más operaciones si se hacen las líneas pares ya que el modelo en cuestión tiene 24899 caras, y 126720 vértices

**Comment by jmg0137** [comment]
Cambiando las caras en lugar de los vértices obtenemos mejores resultados tanto en tiempo como en encriptación. Fix
