### ISSUE TITLE
Aplicar instrucciones VPN UBU para llamar al servidor arquimedes desde cualquier red

### ISSUE THREAD

**Issue by jmg0137** [jmg0137/3D-Viewer-v2.0#55]
A su vez comprobaremos su correcto funcionamiento

**Comment by jmg0137** [comment]
No se si solamente los profesores tienen acceso a https://vpn.ubu.es ya que me intento conectar con mis datos de la UBU y me da erro, permiso denegado

**Comment by alvarag** [comment]
El nombre de usuario es la dirección de correo electrónico, supongo que ya lo habrás probado. Consultaré sobre ello a comunicaciones. Yo acabo de probar y sí que he podido

**Comment by jmg0137** [comment]
Si, he probado correo y DNI, pero en el manual el ejemplo tiene dominio @ubu.es y el mio es @alu.ubu.es, creo que no puedo tener acceso

**Comment by alvarag** [comment]
Supongo que será eso, preguntaré por si fuera posible que tu accedas como alumno

**Comment by jmg0137** [comment]
Damos como finalizada esta tarea aunque no habiendo obtenido los resultados esperados ya que no podemos conectarnos al servicio de VPN de la UBU ya que no tenemos permiso al ser alumnos
